// Code generated by goctl. DO NOT EDIT.
package types

type DistanceMatrix struct {
	Points     [][]float32 `json:"points"`
	Coordinate string      `json:"coordinate,optional"`
	TripMethod int         `json:"method,optional"`
	Speed      int         `json:"speed,optional"`
	Strategy   int         `json:"strategy,optional"`
	TimeSlot   string      `json:"timeslot,optional"`
	Sdk        string      `json:"sdk,optional"`
}

type WaypointsRoute struct {
	Points     [][]float32 `json:"points"`
	Coordinate string      `json:"coordinate,optional"`
	TripMethod int         `json:"method,optional"`
	Speed      int         `json:"speed,optional"`
	Strategy   int         `json:"strategy,optional"`
	TimeSlot   string      `json:"timeslot,optional"`
	Sdk        string      `json:"sdk,optional"`
}

type Route struct {
	Code     int         `json:"code"`
	Message  string      `json:"message"`
	Waypoint [][]float32 `json:"waypoint"`
	Routes   interface{} `json:"routes"`
}

type Edge struct {
	I           int         `json:"i"`
	J           int         `json:"j"`
	Origin      interface{} `json:"origin"`
	Destination interface{} `json:"destination"`
	Duration    float32     `json:"duration"`
	Distance    float32     `json:"distance"`
	Polyline    [][]float32 `json:"polyline"`
	Speed       float32     `json:"speed"`
}

type Options struct {
	Open     bool                   `json:"open"`
	Priority int                    `json:"priority"`
	Strategy map[int]interface{}    `json:"strategy"`
	Method   map[int]interface{}    `json:"method"`
	Option   map[string]interface{} `json:"option"`
}

type ServiceListResponse struct {
	Code int                `json:"code"`
	Msg  string             `json:"msg"`
	Data map[string]Options `json:"data,omitempty"`
}

type DistanceMatrixResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data []Edge `json:"data,omitempty"`
}

type WaypointsRouteResponse struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}
