// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"quantum-matrix/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/matrix",
				Handler: matrixHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/route",
				Handler: routeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/sdks",
				Handler: sdksHandler(serverCtx),
			},
		},
	)
}
