// Command genddl dumps GORM AutoMigrate SQL for DistanceMatrixEdge.
//
// Requires a MySQL DSN (GORM Migrator emits the dialect SQL):
//
//	go run ./scripts/genddl -dsn 'matrix:matrix@tcp(127.0.0.1:3306)/distance_matrix?parseTime=true&charset=utf8mb4'
//
// Prefer Persistence.AutoMigrate=true in privileged environments; this tool
// captures the same Migrator SQL for offline review / locked-down deploys.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"distance-matrix/internal/persist"

	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func main() {
	dsn := flag.String("dsn", os.Getenv("MATRIX_MYSQL_DSN"), "MySQL DSN used by GORM Migrator")
	out := flag.String("out", "scripts/ddl/001_distance_matrix_edge.sql", "output SQL path")
	flag.Parse()
	if strings.TrimSpace(*dsn) == "" {
		fmt.Fprintln(os.Stderr, "genddl: need -dsn or MATRIX_MYSQL_DSN (GORM generates MySQL DDL via Migrator)")
		os.Exit(2)
	}

	root, err := os.Getwd()
	if err != nil {
		fatal(err)
	}
	if _, err := os.Stat(filepath.Join(root, "internal", "persist", "model.go")); err != nil {
		root = filepath.Clean(filepath.Join(root, ".."))
	}

	var buf strings.Builder
	db, err := gorm.Open(mysql.Open(*dsn), &gorm.Config{
		DryRun: true,
		Logger: logger.New(&bufWriter{&buf}, logger.Config{
			SlowThreshold:             time.Second,
			LogLevel:                  logger.Info,
			IgnoreRecordNotFoundError: true,
			Colorful:                  false,
		}),
	})
	if err != nil {
		fatal(err)
	}

	// DryRun AutoMigrate → logger captures CREATE / INDEX statements.
	_ = db.AutoMigrate(&persist.DistanceMatrixEdge{})

	sqlText := sanitizeCapturedSQL(buf.String())
	if strings.TrimSpace(sqlText) == "" {
		fatal(fmt.Errorf("no SQL captured from GORM Migrator; check DSN / DryRun logger"))
	}

	header := `-- Generated by GORM Migrator from internal/persist/model.go
-- Do not hand-edit. Regenerate:
--   go run ./scripts/genddl -dsn 'user:pass@tcp(host:3306)/distance_matrix?parseTime=true&charset=utf8mb4'
--
SET NAMES utf8mb4;

`
	outPath := *out
	if !filepath.IsAbs(outPath) {
		outPath = filepath.Join(root, outPath)
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(outPath, []byte(header+sqlText+"\n"), 0o644); err != nil {
		fatal(err)
	}
	fmt.Println("wrote", outPath)
}

type bufWriter struct{ b *strings.Builder }

func (w *bufWriter) Printf(format string, args ...interface{}) {
	fmt.Fprintf(w.b, format, args...)
	w.b.WriteByte('\n')
}

var (
	sqlStmtStart = regexp.MustCompile(`(?i)\b(CREATE|ALTER)\b`)
	loggerNoise  = regexp.MustCompile(`(?i)^(?:\[.*?\]\s*)+`)
)

func sanitizeCapturedSQL(raw string) string {
	var out []string
	seen := map[string]struct{}{}
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		loc := sqlStmtStart.FindStringIndex(line)
		if loc == nil {
			continue
		}
		stmt := strings.TrimSpace(line[loc[0]:])
		stmt = loggerNoise.ReplaceAllString(stmt, "")
		if stmt == "" {
			continue
		}
		if !strings.HasSuffix(stmt, ";") {
			stmt += ";"
		}
		if _, ok := seen[stmt]; ok {
			continue
		}
		seen[stmt] = struct{}{}
		out = append(out, stmt)
	}
	return strings.Join(out, "\n\n")
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "genddl: %v\n", err)
	os.Exit(1)
}
